return {
	"ibhagwan/fzf-lua",
	event = "VeryLazy",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	opts = function()
		local actions = require("fzf-lua.actions")
		return {
			actions = {
				files = {
					["enter"] = actions.file_edit_or_qf,
					["ctrl-s"] = actions.file_split,
					["ctrl-i"] = actions.file_vsplit,
					["ctrl-t"] = actions.file_tabedit,
					["alt-q"] = actions.file_sel_to_qf,
					["alt-Q"] = actions.file_sel_to_ll,
					["alt-i"] = actions.toggle_ignore,
					["alt-h"] = actions.toggle_hidden,
					["alt-f"] = actions.toggle_follow,
				},
			},
			hls = {
				normal = "Normal",
				border = "FloatBorder",
				preview_normal = "Normal",
				preview_border = "FloatBorder",
			},
			winopts = {
				border = "rounded",
				backdrop = 100,
				preview = {
					border = "rounded",
				},
			},
			keymap = {
				builtin = {
					["ctrl-j"] = "accept",
					["ctrl-l"] = "up",
					["ctrl-k"] = "down",
					["<M-Esc>"] = "hide",
					["<F1>"] = "toggle-help",
					["<F2>"] = "toggle-fullscreen",
					["<F3>"] = "toggle-preview-wrap",
					["<F4>"] = "toggle-preview",
					["<F5>"] = "toggle-preview-cw",
					["<F6>"] = "toggle-preview-behavior",
					["<F7>"] = "toggle-preview-ts-ctx",
					["<F8>"] = "preview-ts-ctx-dec",
					["<F9>"] = "preview-ts-ctx-inc",
					["<S-Left>"] = "preview-reset",
					["<S-down>"] = "preview-page-down",
					["<S-up>"] = "preview-page-up",
					["<M-S-down>"] = "preview-down",
					["<M-S-up>"] = "preview-up",
				},
				fzf = {
					["ctrl-j"] = "accept",
					["ctrl-l"] = "up",
					["ctrl-k"] = "down",
					["ctrl-q"] = "abort",
					["ctrl-u"] = "unix-line-discard",
					["ctrl-f"] = "half-page-down",
					["ctrl-b"] = "half-page-up",
					["ctrl-a"] = "beginning-of-line",
					["ctrl-e"] = "end-of-line",
					["alt-a"] = "toggle-all",
					["alt-g"] = "first",
					["alt-G"] = "last",
					["f3"] = "toggle-preview-wrap",
					["f4"] = "toggle-preview",
					["shift-down"] = "preview-page-down",
					["shift-up"] = "preview-page-up",
				},
			},
		}
	end,
}
